name: project_wp289
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - contourpy=1.2.0
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - icu=73.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - munkres=1.1.4
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.4
  - pillow=10.0.1
  - pip=23.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - qt-main=5.15.2
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - beartype==0.16.4
      - chex==0.1.85
      - cloudpickle==3.0.0
      - cola-ml==0.0.5
      - cola-plum-dispatch==0.1.4
      - colorama==0.4.6
      - decorator==5.1.1
      - dm-tree==0.1.8
      - etils==1.6.0
      - fsspec==2023.12.2
      - gast==0.5.4
      - gpjax==0.8.0
      - importlib-resources==6.1.1
      - jax==0.4.23
      - jaxlib==0.4.23
      - jaxopt==0.8.3
      - jaxtyping==0.2.25
      - ml-dtypes==0.3.2
      - msgpack==1.0.7
      - nest-asyncio==1.6.0
      - opt-einsum==3.3.0
      - optax==0.1.8
      - optree==0.10.0
      - orbax-checkpoint==0.5.2
      - protobuf==4.25.2
      - pytreeclass==0.9.2
      - pyyaml==6.0.1
      - scipy==1.12.0
      - simple-pytree==0.1.7
      - tensorflow-probability==0.19.0
      - tensorstore==0.1.52
      - toolz==0.12.1
      - tqdm==4.66.1
      - typeguard==2.13.3
      - typing-extensions==4.9.0
      - zipp==3.17.0
